import { useCallback, useEffect, useRef, useState } from "react";
import { ArrowDown } from "lucide-react";

import ThinkingAnimation from "../../shared/components/chat/ThinkingAnimation";
import MessageRenderer from "../../shared/components/chat/MessageRenderer";

import { useChats } from "../../shared/context/ChatContext";

const ChatBody = ({ isGenerating = false }) => {
  const { activeChatId, activeChatMessages, isLoadingMessages } = useChats();

  const scrollContainerRef = useRef(null);

  const bottomRef = useRef(null);

  const wasAtBottomRef = useRef(true);

  const programmaticScrollRef = useRef(false);

  const previousMessageCountRef = useRef(activeChatMessages?.length || 0);

  const previousChatIdRef = useRef(activeChatId);

  const scrollAnimationFrameRef = useRef(null);

  const aiScrollPendingRef = useRef(false);

  const [showScrollDown, setShowScrollDown] = useState(false);

  //----->>>> CHECK IF USER IS AT BOTTOM

  const checkIfAtBottom = useCallback(() => {
    const container = scrollContainerRef.current;

    if (!container) {
      return true;
    }

    const distanceFromBottom =
      container.scrollHeight - container.scrollTop - container.clientHeight;

    return distanceFromBottom <= 32;
  }, []);

  //---->>>> CANCEL PENDING SCROLL

  const cancelPendingScroll = useCallback(() => {
    if (scrollAnimationFrameRef.current) {
      cancelAnimationFrame(scrollAnimationFrameRef.current);

      scrollAnimationFrameRef.current = null;
    }

    aiScrollPendingRef.current = false;
  }, []);

  //----->>>> SCROLL TO BOTTOM

  const scrollToBottom = useCallback(
    (behavior = "smooth") => {
      const container = scrollContainerRef.current;

      if (!container) {
        return;
      }

      cancelPendingScroll();

      programmaticScrollRef.current = true;

      container.scrollTo({
        top: container.scrollHeight - container.clientHeight,
        behavior,
      });

      wasAtBottomRef.current = true;

      setShowScrollDown(false);

      //---->>> Immediate scroll

      if (behavior === "auto") {
        programmaticScrollRef.current = false;
        return;
      }

      // Release programmatic-scroll lock after smooth scrolling reaches bottom

      const releaseProgrammaticScroll = () => {
        const currentContainer = scrollContainerRef.current;

        if (!currentContainer) {
          programmaticScrollRef.current = false;
          return;
        }

        const atBottom = checkIfAtBottom();

        if (atBottom) {
          programmaticScrollRef.current = false;

          wasAtBottomRef.current = true;

          setShowScrollDown(false);

          return;
        }

        scrollAnimationFrameRef.current = requestAnimationFrame(
          releaseProgrammaticScroll,
        );
      };

      scrollAnimationFrameRef.current = requestAnimationFrame(
        releaseProgrammaticScroll,
      );
    },
    [cancelPendingScroll, checkIfAtBottom],
  );

  //---->>>> FOLLOW AI RESPONSE

  const followAIResponse = useCallback(() => {
    if (!wasAtBottomRef.current) {
      return;
    }

    if (aiScrollPendingRef.current) {
      return;
    }

    aiScrollPendingRef.current = true;

    requestAnimationFrame(() => {
      aiScrollPendingRef.current = false;

      const container = scrollContainerRef.current;

      if (!container) {
        return;
      }

      if (!wasAtBottomRef.current) {
        return;
      }

      programmaticScrollRef.current = true;

      container.scrollTo({
        top: container.scrollHeight - container.clientHeight,
        behavior: "smooth",
      });

      requestAnimationFrame(() => {
        requestAnimationFrame(() => {
          programmaticScrollRef.current = false;
        });
      });
    });
  }, []);

  //------>>>> HANDLE USER SCROLL

  useEffect(() => {
    const container = scrollContainerRef.current;

    if (!container || isLoadingMessages) {
      return;
    }

    const handleScroll = () => {
      // Ignore scroll events generated by our own programmatic scrolling.
      if (programmaticScrollRef.current) {
        return;
      }

      const atBottom = checkIfAtBottom();

      wasAtBottomRef.current = atBottom;

      // If user moves away from bottom, cancel pending automatic scrolling.
      if (!atBottom) {
        cancelPendingScroll();
      }

      setShowScrollDown(!atBottom);
    };

    container.addEventListener("scroll", handleScroll, {
      passive: true,
    });

    handleScroll();

    return () => {
      container.removeEventListener("scroll", handleScroll);

      cancelPendingScroll();
    };
  }, [checkIfAtBottom, cancelPendingScroll, isLoadingMessages, activeChatId]);

  //----->>>> CHAT SWITCH

  useEffect(() => {
    const chatChanged = previousChatIdRef.current !== activeChatId;

    if (!chatChanged) {
      return;
    }

    previousChatIdRef.current = activeChatId;

    requestAnimationFrame(() => {
      requestAnimationFrame(() => {
        scrollToBottom("auto");
      });
    });
  }, [activeChatId, scrollToBottom]);

  //------>>>> NEW MESSAGE

  useEffect(() => {
    const messages = activeChatMessages || [];

    const currentCount = messages.length;

    const previousCount = previousMessageCountRef.current;

    const messageWasAdded = currentCount > previousCount;

    previousMessageCountRef.current = currentCount;

    if (!messageWasAdded || messages.length === 0) {
      return;
    }

    const lastMessage = messages[messages.length - 1];

    //------->>> USER MESSAGE

    if (lastMessage?.role === "user") {
      requestAnimationFrame(() => {
        requestAnimationFrame(() => {
          scrollToBottom("smooth");
        });
      });

      return;
    }

    //----->>>> ASSISTANT MESSAGE

    if (lastMessage?.role === "assistant") {
      followAIResponse();
    }
  }, [activeChatMessages, followAIResponse, scrollToBottom]);

  //----->>>> AI GENERATION

  useEffect(() => {
    if (!isGenerating) {
      return;
    }

    if (!wasAtBottomRef.current) {
      return;
    }

    followAIResponse();
  }, [isGenerating, followAIResponse]);

  //----->>>> AI STREAMING

  useEffect(() => {
    if (!isGenerating) {
      return;
    }

    if (!wasAtBottomRef.current) {
      return;
    }

    followAIResponse();
  }, [activeChatMessages, isGenerating, followAIResponse]);

  //----->>>> INITIAL CHAT LOAD

  useEffect(() => {
    if (!activeChatId || isLoadingMessages) {
      return;
    }

    requestAnimationFrame(() => {
      requestAnimationFrame(() => {
        scrollToBottom("auto");
      });
    });
  }, [activeChatId, isLoadingMessages, scrollToBottom]);

  //------>>>>> CLEANUP

  useEffect(() => {
    return () => {
      cancelPendingScroll();
    };
  }, [cancelPendingScroll]);

  //---->>>> LOADING STATE

  if (isLoadingMessages) {
    return (
      <div
        className="
          flex
          h-full
          min-h-0
          items-center
          justify-center
          px-4
        "
      >
        <div className="text-sm text-neutral-500">Loading conversation...</div>
      </div>
    );
  }

  //----->>>> MAIN CHAT BODY

  return (
    <section
      ref={scrollContainerRef}
      className="
        relative
        h-full
        min-h-0
        w-full
        overflow-y-auto
        overflow-x-hidden
        [scrollbar-color:#404040_transparent]
      "
      style={{
        scrollbarColor: "#404040 transparent",
      }}
    >
      {/*------>>>> MESSAGE CONTENT*/}

      <div
        className="
          mx-auto
          w-full
          max-w-4xl
          px-3
          pb-44
          pt-4

          sm:px-6
          sm:pb-48
          sm:pt-6
        "
      >
        {/* ------->>> EXISTING MESSAGES */}

        {activeChatMessages.map((message, index) => (
          <MessageRenderer
            key={message.id ?? message._id ?? `${message.role}-${index}`}
            message={message}
          />
        ))}

        {/*------>>>> AI THINKING */}

        {isGenerating && (
          <div className="flex justify-start">
            <ThinkingAnimation />
          </div>
        )}

        {/* ------>>>> BOTTOM SENTINEL */}

        <div ref={bottomRef} className="h-px w-full" aria-hidden="true" />
      </div>

      {/*----->>>> SCROLL TO BOTTOM BUTTON */}

      {showScrollDown && (
        <button
          type="button"
          onClick={() => scrollToBottom("smooth")}
          aria-label="Scroll to latest message"
          title="Scroll to latest message"
          className="
            fixed
            bottom-[145px]
            left-1/2
            z-[50]
            flex
            h-10
            w-10
            -translate-x-1/2
            items-center
            justify-center
            rounded-full
            border
            border-neutral-700
            bg-neutral-900/95
            text-neutral-300
            shadow-[0_8px_30px_rgba(0,0,0,0.45)]
            backdrop-blur-md
            transition-all
            duration-200
            hover:border-violet-500/60
            hover:bg-neutral-800
            hover:text-white
            hover:shadow-[0_8px_35px_rgba(99,102,241,0.25)]
            active:scale-95
cursor-pointer
            sm:bottom-[175px]
          "
        >
          <ArrowDown size={19} strokeWidth={2.5} />
        </button>
      )}
    </section>
  );
};

export default ChatBody;
