export const formatChatResponse = (content = "") => {
  if (!content) return "";

  let text = String(content);

  /*
   * 1. Normalize line endings
   */
  text = text.replace(/\r\n/g, "\n");
  text = text.replace(/\r/g, "\n");

  /*
   * 2. Remove accidental "Copy" labels generated by AI
   *
   * Examples:
   * java**Copy**
   * text**Copy**
   * cpp **Copy**
   * python Copy
   */
  text = text.replace(
    /^\s*(java|javascript|typescript|python|cpp|c\+\+|c|csharp|c#|go|rust|sql|bash|shell|text|json|xml|html|css|jsx|tsx|markdown|md)\s*\*\*Copy\*\*\s*$/gim,
    "",
  );

  text = text.replace(
    /^\s*(java|javascript|typescript|python|cpp|c\+\+|c|csharp|c#|go|rust|sql|bash|shell|text|json|xml|html|css|jsx|tsx|markdown|md)\s+Copy\s*$/gim,
    "",
  );

  /*
   * 3. Remove standalone Copy labels
   */
  text = text.replace(/^\s*\*\*Copy\*\*\s*$/gim, "");

  /*
   * 4. Fix common malformed LaTeX artifacts
   *
   * Example:
   * O(n)*O*(n)
   * O(n2)*O*(*n*2)
   *
   * These commonly appear when the AI mixes Markdown
   * emphasis with mathematical notation.
   */

  text = text.replace(
    /([A-Za-z])\(([^()\n]+)\)\*([A-Za-z])\*\(([^()\n]+)\)/g,
    "$1($2)",
  );

  /*
   * 5. Normalize common Big-O expressions
   */

  text = text.replace(
    /\bO\s*\(\s*n\s*\)\s*\*\s*O\s*\*\s*\(\s*n\s*\)/gi,
    "O(n)",
  );

  text = text.replace(
    /\bO\s*\(\s*n\s*2\s*\)\s*\*\s*O\s*\*\s*\(\s*n\s*\*?\s*2\s*\)/gi,
    "O(n²)",
  );

  /*
   * 6. Normalize malformed Markdown emphasis around
   * mathematical expressions.
   *
   * O(n2)*O*(*n*2)
   *        ↓
   * O(n²)
   */
  text = text.replace(
    /\bO\s*\(\s*n\s*2\s*\)\s*\*\s*O\s*\*\s*\(\s*n\s*\*?\s*2\s*\)/gi,
    "O(n²)",
  );

  /*
   * 7. Remove excessive blank lines
   */
  text = text.replace(/\n{3,}/g, "\n\n");

  /*
   * 8. Ensure headings have clean spacing
   */
  text = text.replace(/\n([ \t]*#{1,6}[^\n]+)/g, "\n\n$1");

  /*
   * Don't create too many blank lines before the first heading.
   */
  text = text.replace(/^\n+/, "");

  /*
   * 9. Ensure unordered lists have spacing
   */
  text = text.replace(/([^\n])\n([ \t]*[-*+]\s)/g, "$1\n\n$2");

  /*
   * 10. Ensure numbered lists have spacing
   */
  text = text.replace(/([^\n])\n([ \t]*\d+\.\s)/g, "$1\n\n$2");

  /*
   * 11. Clean excessive spaces around horizontal rules
   */
  text = text.replace(/\n[ \t]*---+[ \t]*\n/g, "\n\n---\n\n");

  /*
   * 12. Remove spaces at the end of lines
   */
  text = text.replace(/[ \t]+\n/g, "\n");

  /*
   * 13. Final trim
   */
  return text.trim();
};
